"use client";

import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, FileText, Loader2, RefreshCw, UploadCloud, X } from "lucide-react";
import toast from "react-hot-toast";
import { BulkUploadDialog } from "@/app/components/bulk-upload/BulkUploadDialog";
import { usePaymentPermissions } from "@/app/components/payments/usePaymentPermissions";
import { PaymentStatusBadge, paymentAmount, paymentDate, paymentTypeLabel } from "@/app/components/payments/payment-display";
import { confirmPayment, getAdminAllPaymentStatus, getPaymentProofBlobUrl, getPendingPayments, rejectPayment, type PendingPayment } from "@/app/lib/payments-api";
import { getApiErrorMessage } from "@/app/lib/api-client";

const PAGE_SIZE = 20;
type View = "queue" | "history";
type Decision = { payment: PendingPayment; kind: "confirm" | "reject" };

function DecisionDialog({ decision, pending, onClose, onConfirm }: { decision: Decision; pending: boolean; onClose: () => void; onConfirm: (reason: string) => void }) {
  const [reason, setReason] = useState("");
  const confirming = decision.kind === "confirm";
  return <div role="dialog" aria-modal="true" aria-labelledby="payment-decision-title" className="fixed inset-0 z-[70] grid place-items-center bg-black/60 p-4"><form onSubmit={(event) => { event.preventDefault(); onConfirm(reason.trim()); }} className="card-admin w-full max-w-md space-y-5 rounded-3xl p-6 shadow-2xl"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-amber-600">Payment decision</p><h2 id="payment-decision-title" className="mt-1 text-xl font-bold">{confirming ? "Confirm and credit savings?" : "Reject this payment?"}</h2></div><button type="button" onClick={onClose} disabled={pending} aria-label="Close" className="rounded-full border p-2"><X className="h-4 w-4" /></button></div><p className="text-sm admin-text-muted">{paymentAmount(decision.payment.amountPaid, decision.payment.currency)} from {decision.payment.payerName || decision.payment.payerEmail || "this member"}. {confirming ? "The backend will credit savings if the confirmation succeeds. Verify the proof and reference first." : "The payment will not be credited."}</p>{!confirming && <label className="grid gap-2 text-sm font-semibold">Reason for rejection<textarea required rows={3} value={reason} onChange={(event) => setReason(event.target.value)} className="input-admin rounded-xl p-3 text-sm outline-none" placeholder="Explain why this payment was rejected" /></label>}<div className="flex justify-end gap-2"><button type="button" onClick={onClose} disabled={pending} className="rounded-full border px-4 py-2.5 text-sm font-semibold">Cancel</button><button type="submit" disabled={pending || (!confirming && !reason)} className={`inline-flex items-center gap-2 rounded-full px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50 ${confirming ? "bg-[#171717]" : "bg-red-700"}`}>{pending && <Loader2 className="h-4 w-4 animate-spin" />}{confirming ? "Confirm payment" : "Reject payment"}</button></div></form></div>;
}

export default function ContributionsPage() {
  const queryClient = useQueryClient();
  const permissions = usePaymentPermissions();
  const [view, setView] = useState<View>("queue");
  const [page, setPage] = useState(1);
  const [type, setType] = useState("");
  const [status, setStatus] = useState<"" | "Draft" | "PendingConfirmation" | "Confirmed" | "Rejected">("");
  const [fromDate, setFromDate] = useState("");
  const [toDate, setToDate] = useState("");
  const [reference, setReference] = useState("");
  const [onlyAssignedToMe, setOnlyAssignedToMe] = useState(false);
  const [submittedByUserId, setSubmittedByUserId] = useState("");
  const [selected, setSelected] = useState<PendingPayment | null>(null);
  const [decision, setDecision] = useState<Decision | null>(null);
  const [showBulkUpload, setShowBulkUpload] = useState(false);
  const [proofUrl, setProofUrl] = useState<string | null>(null);
  const [proofError, setProofError] = useState<string | null>(null);
  const [proofLoading, setProofLoading] = useState(false);

  useEffect(() => () => { if (proofUrl) URL.revokeObjectURL(proofUrl); }, [proofUrl]);

  const queue = useQuery({ queryKey: ["pending-payments", page, type, fromDate, toDate, reference, onlyAssignedToMe], queryFn: () => getPendingPayments({ page, pageSize: PAGE_SIZE, type, fromDate, toDate, reference, onlyAssignedToMe }), enabled: view === "queue" && permissions.canConfirm });
  const history = useQuery({ queryKey: ["all-payment-status", page, status, type, fromDate, toDate, reference, submittedByUserId], queryFn: () => getAdminAllPaymentStatus({ page, pageSize: PAGE_SIZE, status: status || undefined, type, fromDate, toDate, reference, submittedByUserId }), enabled: view === "history" });
  const result = view === "queue" ? queue : history;

  const confirmation = useMutation({ mutationFn: (id: string) => confirmPayment(id), onSuccess: () => { toast.success("Payment confirmed; savings credited by the backend."); setDecision(null); setSelected(null); queryClient.invalidateQueries({ queryKey: ["pending-payments"] }); queryClient.invalidateQueries({ queryKey: ["all-payment-status"] }); }, onError: (error) => toast.error(getApiErrorMessage(error)) });
  const rejection = useMutation({ mutationFn: ({ id, reason }: { id: string; reason: string }) => rejectPayment(id, { reason }), onSuccess: () => { toast.success("Payment rejected."); setDecision(null); setSelected(null); queryClient.invalidateQueries({ queryKey: ["pending-payments"] }); queryClient.invalidateQueries({ queryKey: ["all-payment-status"] }); }, onError: (error) => toast.error(getApiErrorMessage(error)) });

  function changeView(next: View) { setView(next); setPage(1); setSelected(null); }
  function resetPage() { setPage(1); setSelected(null); }
  async function openProof(fileName: string) {
    setProofLoading(true); setProofError(null);
    try { setProofUrl(await getPaymentProofBlobUrl(fileName, "admin")); }
    catch (error) { setProofError(getApiErrorMessage(error)); }
    finally { setProofLoading(false); }
  }

  return <div className="mx-auto max-w-7xl space-y-6 pb-14 admin-text">
    <BulkUploadDialog kind="Savings" open={showBulkUpload} onClose={() => setShowBulkUpload(false)} />
    <header className="relative overflow-hidden rounded-3xl bg-[#181817] p-6 text-white md:p-8"><div className="pointer-events-none absolute -right-20 -top-24 h-64 w-64 rounded-full bg-amber-400/15 blur-3xl" /><div className="relative flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-amber-300">Savings administration</p><h1 className="mt-2 text-3xl font-bold tracking-tight md:text-4xl">Payments & contributions</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/70">Review payment submissions before crediting savings and see the full payment history.</p></div><button type="button" onClick={() => setShowBulkUpload(true)} className="inline-flex items-center gap-2 rounded-full border border-white/25 px-4 py-2.5 text-sm font-semibold text-white hover:bg-white/10"><UploadCloud className="h-4 w-4" /> Bulk savings upload</button></div></header>

    <section className="card-admin rounded-3xl p-5 md:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Payment records</h2><p className="mt-1 text-sm admin-text-muted">The review queue is separate from confirmed, rejected, and draft history.</p></div><button type="button" onClick={() => result.refetch()} disabled={result.isFetching || (view === "queue" && !permissions.canConfirm)} className="inline-flex items-center gap-2 rounded-full border px-4 py-2 text-sm font-semibold disabled:opacity-50" style={{ borderColor: "var(--admin-border)" }}><RefreshCw className={`h-4 w-4 ${result.isFetching ? "animate-spin" : ""}`} /> Refresh</button></div>
      <div className="mt-5 flex gap-2"><button type="button" aria-pressed={view === "queue"} onClick={() => changeView("queue")} className={`rounded-full px-4 py-2 text-sm font-semibold ${view === "queue" ? "bg-[#171717] text-white" : "border"}`} style={view === "queue" ? undefined : { borderColor: "var(--admin-border)" }}>Needs review</button><button type="button" aria-pressed={view === "history"} onClick={() => changeView("history")} className={`rounded-full px-4 py-2 text-sm font-semibold ${view === "history" ? "bg-[#171717] text-white" : "border"}`} style={view === "history" ? undefined : { borderColor: "var(--admin-border)" }}>All payment statuses</button></div>
      <div className="mt-5 grid gap-3 border-t pt-5 sm:grid-cols-2 lg:grid-cols-4" style={{ borderColor: "var(--admin-border)" }}><label className="grid gap-1.5 text-xs font-semibold admin-text-muted">Contribution type<select value={type} onChange={(event) => { setType(event.target.value); resetPage(); }} className="input-admin rounded-xl px-3 py-2.5 text-sm outline-none"><option value="">All types</option><option value="ShareCapital">Share capital</option><option value="SavingsContribution">Savings contribution</option><option value="CommitmentFee">Commitment fee</option></select></label><label className="grid gap-1.5 text-xs font-semibold admin-text-muted">From date<input type="date" value={fromDate} onChange={(event) => { setFromDate(event.target.value); resetPage(); }} className="input-admin rounded-xl px-3 py-2.5 text-sm outline-none" /></label><label className="grid gap-1.5 text-xs font-semibold admin-text-muted">To date<input type="date" value={toDate} onChange={(event) => { setToDate(event.target.value); resetPage(); }} className="input-admin rounded-xl px-3 py-2.5 text-sm outline-none" /></label><label className="grid gap-1.5 text-xs font-semibold admin-text-muted">Reference<input value={reference} onChange={(event) => { setReference(event.target.value); resetPage(); }} placeholder="Search reference" className="input-admin rounded-xl px-3 py-2.5 text-sm outline-none" /></label></div>
      <div className="mt-4 flex flex-wrap items-end gap-4">{view === "queue" ? <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={onlyAssignedToMe} onChange={(event) => { setOnlyAssignedToMe(event.target.checked); resetPage(); }} className="h-4 w-4 accent-amber-500" /> Assigned to me only</label> : <><label className="grid gap-1.5 text-xs font-semibold admin-text-muted">Status<select value={status} onChange={(event) => { setStatus(event.target.value as typeof status); resetPage(); }} className="input-admin rounded-xl px-3 py-2.5 text-sm outline-none"><option value="">All statuses</option><option value="Draft">Draft</option><option value="PendingConfirmation">Pending confirmation</option><option value="Confirmed">Confirmed</option><option value="Rejected">Rejected</option></select></label><label className="grid gap-1.5 text-xs font-semibold admin-text-muted">Submitted by user ID<input value={submittedByUserId} onChange={(event) => { setSubmittedByUserId(event.target.value); resetPage(); }} placeholder="Optional user ID" className="input-admin rounded-xl px-3 py-2.5 text-sm outline-none" /></label></>}</div>
    </section>

    <section aria-label={view === "queue" ? "Pending payment submissions" : "Payment history"} className="grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(19rem,0.8fr)] xl:items-start"><div className="card-admin overflow-hidden rounded-3xl"><div className="border-b px-5 py-4" style={{ borderColor: "var(--admin-border)" }}><h2 className="text-lg font-semibold">{view === "queue" ? "Awaiting confirmation" : "All payment statuses"}</h2><p className="mt-1 text-xs admin-text-muted">{result.data ? `${result.data.totalCount} matching payment${result.data.totalCount === 1 ? "" : "s"}` : "Payment submissions"}</p></div>
      {view === "queue" && permissions.isLoading ? <p role="status" className="p-8 text-sm admin-text-muted">Checking review access...</p> : view === "queue" && !permissions.canConfirm ? <p className="p-8 text-sm admin-text-muted">You do not have permission to confirm member payments.</p> : result.isLoading ? <p role="status" className="flex items-center justify-center gap-2 p-10 text-sm admin-text-muted"><Loader2 className="h-4 w-4 animate-spin" /> Loading payments...</p> : result.isError ? <div role="alert" className="p-8 text-sm text-red-700"><p>{getApiErrorMessage(result.error)}</p><button type="button" onClick={() => result.refetch()} className="mt-2 font-semibold underline">Retry</button></div> : !result.data?.items?.length ? <p className="p-10 text-center text-sm admin-text-muted">No payments match this view.</p> : <div className="divide-y" style={{ borderColor: "var(--admin-border)" }}>{result.data.items.map((payment) => <button key={payment.id} type="button" onClick={() => setSelected(payment)} className={`flex w-full flex-wrap items-center justify-between gap-3 px-5 py-4 text-left hover:bg-amber-400/5 ${selected?.id === payment.id ? "bg-amber-400/10" : ""}`}><div className="min-w-0"><p className="truncate text-sm font-semibold">{payment.payerName || payment.payerEmail || "Member"}</p><p className="mt-1 truncate text-xs admin-text-muted">{paymentTypeLabel(payment.type)} · {paymentDate(payment.submittedAt ?? payment.paymentDate)}</p></div><div className="text-right"><p className="text-sm font-bold">{paymentAmount(payment.amountPaid, payment.currency)}</p><div className="mt-1"><PaymentStatusBadge status={payment.status} /></div></div></button>)}</div>}
      {result.data && result.data.totalPages > 1 && <nav aria-label="Payment pages" className="flex items-center justify-between gap-2 border-t p-4 text-sm" style={{ borderColor: "var(--admin-border)" }}><button type="button" disabled={page <= 1 || result.isFetching} onClick={() => { setPage((value) => value - 1); setSelected(null); }} className="rounded-full border px-4 py-2 disabled:opacity-40">Previous</button><span className="text-xs admin-text-muted">Page {result.data.pageNumber} of {result.data.totalPages}</span><button type="button" disabled={page >= result.data.totalPages || result.isFetching} onClick={() => { setPage((value) => value + 1); setSelected(null); }} className="rounded-full border px-4 py-2 disabled:opacity-40">Next</button></nav>}</div>
      <aside className="card-admin rounded-3xl p-5 md:p-6 xl:sticky xl:top-24">{!selected ? <div className="py-12 text-center text-sm admin-text-muted"><FileText className="mx-auto mb-3 h-7 w-7 text-amber-500" />Select a payment to review its details.</div> : <><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-amber-600">Payment details</p><h2 className="mt-2 text-2xl font-bold">{paymentAmount(selected.amountPaid, selected.currency)}</h2><p className="mt-1 text-sm admin-text-muted">{selected.payerName || selected.payerEmail || "Member"}</p></div><PaymentStatusBadge status={selected.status} /></div><dl className="mt-6 space-y-3 text-sm">{[["Type", paymentTypeLabel(selected.type)], ["Payment date", paymentDate(selected.paymentDate)], ["Submitted", paymentDate(selected.submittedAt)], ["Reference", selected.interacReferenceNumber || "—"], ["Method", selected.method || "—"], ["Note", selected.note || "—"], ["Assigned to", selected.assignedToName || "—"]].map(([label, value]) => <div key={label} className="flex justify-between gap-4 border-b pb-3" style={{ borderColor: "var(--admin-border)" }}><dt className="admin-text-muted">{label}</dt><dd className="max-w-[65%] text-right font-medium break-words">{value}</dd></div>)}</dl>{selected.proofFileName ? <button type="button" onClick={() => openProof(selected.proofFileName!)} disabled={proofLoading} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl border px-4 py-3 text-sm font-semibold disabled:opacity-50" style={{ borderColor: "var(--admin-border)" }}><FileText className="h-4 w-4" /> {proofLoading ? "Opening proof..." : "View payment proof"}</button> : <p className="mt-5 rounded-xl border border-dashed p-3 text-xs admin-text-muted">No proof of payment attached.</p>}{proofError && <p role="alert" className="mt-3 text-xs text-red-700">{proofError}</p>}{view === "queue" && permissions.canConfirm && <div className="mt-6 flex gap-3 border-t pt-5" style={{ borderColor: "var(--admin-border)" }}><button type="button" onClick={() => setDecision({ payment: selected, kind: "reject" })} className="flex-1 rounded-full border border-red-200 px-4 py-2.5 text-sm font-semibold text-red-700">Reject</button><button type="button" onClick={() => setDecision({ payment: selected, kind: "confirm" })} className="inline-flex flex-1 items-center justify-center gap-2 rounded-full bg-[#171717] px-4 py-2.5 text-sm font-semibold text-white"><Check className="h-4 w-4" /> Confirm</button></div>}</>}</aside>
    </section>

    {decision && <DecisionDialog decision={decision} pending={confirmation.isPending || rejection.isPending} onClose={() => setDecision(null)} onConfirm={(reason) => decision.kind === "confirm" ? confirmation.mutate(decision.payment.id) : rejection.mutate({ id: decision.payment.id, reason })} />}
    {proofUrl && <div role="dialog" aria-modal="true" aria-label="Payment proof" className="fixed inset-0 z-[80] grid place-items-center bg-black/75 p-4"><div className="flex max-h-[90vh] w-full max-w-4xl flex-col overflow-hidden rounded-2xl bg-white"><div className="flex items-center justify-between border-b p-4"><p className="font-semibold">Payment proof</p><button type="button" onClick={() => setProofUrl(null)} aria-label="Close proof"><X className="h-5 w-5" /></button></div><iframe src={proofUrl} title="Payment proof" className="h-[70vh] w-full" /></div></div>}
  </div>;
}
